#!/bin/sh /etc/rc.common


. /usr/share/libubox/jshn.sh

START=90
STOP=10

USE_PROCD=1
NAME=mcast-pa
PROG=/sbin/mcast-pa

start_service() {
	UPSTREAM=""

	active_upstream() {
		[ -n "$UPSTREAM" ] && return

		config_get upstream $1 upstream

		for upstrm in $upstream; do
			[ "$(cat /sys/class/net/$upstrm/operstate 2>/dev/null)" == "up" ] || continue

			json_load "$(devstatus $upstrm 2>/dev/null)" 2>/dev/null
			json_get_var up up 0
			if [ $up -eq 1 ]; then
				UPSTREAM="$upstrm"
				break
			fi
		done
	}

	config_load mcproxy
	config_foreach active_upstream instance

	if [ -n $UPSTREAM ]; then
		procd_open_instance
		procd_set_param command $PROG --wan $UPSTREAM
		procd_set_param respawn
		procd_close_instance
	fi
}

service_triggers()
{
	procd_add_reload_trigger network mcproxy
}
